# pyproject.toml

[build-system]
requires = ["setuptools>=61.0.0", "wheel", "django>=3.0", "djangorestframework==3.13.1"]
build-backend = "setuptools.build_meta"

[project]
name = "djangorestframework-simple-apikey"
version = "0.0.0"