name: Deploy


on:
  release:
    types: [published]

jobs:
  test:
    name: Testing Django REST Simple API Key
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          [
            "3.10",
            "3.11",
          ]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          make install
      - name: Run Tests
        run: |
          make test

  build-n-publish:
    name: Build and publish Python 🐍 distributions 📦 to PyPI
    needs: [ test ]
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@master
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
      - name: Install pypa/build
        run: >-
          python -m
          pip install
          build
          --user
      - name: Build a binary wheel and a source tarball
        run: >-
          python -m
          build
          --sdist
          --wheel
          --outdir dist/
      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1